import { z } from "zod";
import { locales } from "@/i18n/locales";

const code = z.string().trim().regex(/^[A-Z0-9][A-Z0-9_-]{0,63}$/);
const serviceAddressPartsSchema = z.object({ road: z.string().max(200).optional(), suburb: z.string().max(200).optional(), city: z.string().max(200).optional(), state: z.string().max(200).optional(), postcode: z.string().max(32).optional(), country: z.string().max(200).optional(), countryCode: z.string().length(2).optional() }).strict();
export const serviceLocationSchema = z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), displayName: z.string().trim().min(3).max(500), attribution: z.literal("© OpenStreetMap contributors"), address: serviceAddressPartsSchema.optional() }).strict();
const system = z.discriminatedUnion("systemSource", [
  z.object({ systemSource: z.literal("SOLARDREAM"), assetId: z.string().uuid() }).strict(),
  z.object({ systemSource: z.literal("EXTERNAL"), systemDetails: z.object({ systemSizeKw: z.coerce.number().positive().max(1000), inverterBrandCode: code, roofTypeCode: code }).strict() }).strict(),
]);
export const multiServiceQuoteSchema = z.object({ offeringSlugs: z.array(z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)).min(1).max(20).refine((items) => new Set(items).size === items.length), system, promoCode: z.string().trim().min(3).max(64).optional(), website: z.string().max(0).optional() }).strict();
export const multiServiceConfirmSchema = z.object({ quoteRef: z.string().regex(/^qv1\.[0-9a-f-]{36}\.[A-Za-z0-9_-]{43}\.[A-Za-z0-9_-]{43}$/), action: z.enum(["CHECKOUT", "REQUEST_QUOTE"]), locale: z.enum(locales), appointmentDate: z.coerce.date(), location: serviceLocationSchema.optional(), contact: z.object({ fullName: z.string().trim().min(2).max(160), phone: z.string().trim().min(8).max(32), email: z.string().trim().email().max(254), serviceAddress: z.string().trim().min(10).max(1000) }).strict(), necessaryConsent: z.literal(true), customerNotes: z.string().trim().max(2000).optional() }).strict();
export type MultiServiceQuoteInput = z.input<typeof multiServiceQuoteSchema>;
export type MultiServiceConfirmInput = z.input<typeof multiServiceConfirmSchema>;

export const serviceOptionAdminSchema = z.object({ kind: z.enum(["INVERTER_BRAND", "ROOF_TYPE"]), code, label: z.object({ en: z.string().trim().min(1).max(200), th: z.string().trim().min(1).max(200) }).strict(), isActive: z.boolean(), sortOrder: z.number().int().min(-10000).max(10000) }).strict();
export const serviceBundleAdminSchema = z.object({ code, name: z.object({ en: z.string().trim().min(1).max(200), th: z.string().trim().min(1).max(200) }).strict(), discountBps: z.number().int().min(0).max(10000), minimumDistinctItems: z.number().int().min(2).max(20), offeringIds: z.array(z.string().uuid()).max(50), isActive: z.boolean() }).strict();
export const servicePromotionAdminSchema = z.object({ code: z.string().trim().min(3).max(64), name: z.object({ en: z.string().trim().min(1).max(200), th: z.string().trim().min(1).max(200) }).strict(), discountType: z.enum(["PERCENT_BPS", "FIXED_SATANG"]), value: z.number().int().positive(), minimumSubtotalSatang: z.number().int().nonnegative(), maximumDiscountSatang: z.number().int().nonnegative().nullable(), usageLimit: z.number().int().positive().nullable(), perActorLimit: z.number().int().positive().max(100), eligibility: z.array(z.object({ offeringId: z.string().uuid().nullable(), systemSource: z.enum(["SOLARDREAM", "EXTERNAL"]).nullable(), minimumSystemKw: z.number().positive().nullable(), maximumSystemKw: z.number().positive().nullable() }).strict().refine((rule) => rule.minimumSystemKw === null || rule.maximumSystemKw === null || rule.minimumSystemKw <= rule.maximumSystemKw)).max(100), isActive: z.boolean() }).strict().refine((promotion) => promotion.discountType !== "PERCENT_BPS" || promotion.value <= 10000, { message: "Percentage promotion cannot exceed 10000 basis points.", path: ["value"] });
