import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { isSameOrigin } from "@/lib/privacyConsent";
import { resolveServiceActor } from "@/lib/serviceApi";
import { enforcePortalRateLimit } from "@/lib/portalRateLimit";
import { trackUmamiServerEvent } from "@/utils/analytics-server";

const schema = z.object({ event: z.enum(["service_catalog_viewed","service_viewed","service_quote_created","service_checkout_started","service_order_confirmed","service_quotation_requested","service_custom_quote_requested"]), locale: z.enum(["en","th"]), serviceSku: z.string().trim().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/).optional(), serviceCount: z.number().int().min(0).max(20).optional(), systemClass: z.enum(["SOLARDREAM","EXTERNAL","OVER_20KW"]).optional() }).strict();
export async function POST(request: NextRequest) { try { if (!isSameOrigin(request)) return NextResponse.json({ success: false }, { status: 403 }); const consentRaw = request.cookies.get("solardream_consent")?.value; const consent = consentRaw ? JSON.parse(decodeURIComponent(consentRaw)) as unknown : null; if (!consent || typeof consent !== "object" || Array.isArray(consent) || (consent as Record<string, unknown>).analytics !== true) return NextResponse.json({ success: true, tracked: false }, { status: 202 }); const subject = await resolveServiceActor(request); const rate = await enforcePortalRateLimit({ namespace: "service-analytics", identity: subject.actor.actorHash, limit: 30, windowSeconds: 60 }); if (!rate.allowed) return NextResponse.json({ success: true, tracked: false }, { status: 202 }); const input = schema.parse(await request.json()); const result = await trackUmamiServerEvent({ eventName: input.event, featureFlagKey: "track_service_commerce", url: "/services", properties: { locale: input.locale, service_sku: input.serviceSku, service_count: input.serviceCount, system_class: input.systemClass, actor_type: subject.actor.userId ? "member" : "guest", occurred_at: new Date().toISOString() } }); return NextResponse.json({ success: true, tracked: result.ok }, { status: 202, headers: { "Cache-Control": "private, no-store" } }); } catch { return NextResponse.json({ success: false }, { status: 400 }); } }
