/*
 * Generated from routes.ts. This surface deliberately contains only the
 * lazy handlers assigned to the customer application.
 */
import { Elysia } from "elysia";

import { adaptLegacyHandler } from "./legacy-adapter";

export const customerApiRoutes = new Elysia({
  name: "solardream-customer-api-routes",
  prefix: "/api",
})
  .post("/account-link", adaptLegacyHandler(() => import("@/server/api/account-link/route"), "POST"))
  .post("/analyze-roof", adaptLegacyHandler(() => import("@/server/api/analyze-roof/route"), "POST"))
  .get("/auth/callback", adaptLegacyHandler(() => import("@/server/api/auth/callback/route"), "GET"))
  .get("/auth/discourse-sso", adaptLegacyHandler(() => import("@/server/api/auth/discourse-sso/route"), "GET"))
  .get("/auth/line/callback", adaptLegacyHandler(() => import("@/server/api/auth/line/callback/route"), "GET"))
  .post("/auth/link-line", adaptLegacyHandler(() => import("@/server/api/auth/link-line/route"), "POST"))
  .post("/auth/sync-user", adaptLegacyHandler(() => import("@/server/api/auth/sync-user/route"), "POST"))
  .post("/auth/unlink-line", adaptLegacyHandler(() => import("@/server/api/auth/unlink-line/route"), "POST"))
  .delete("/auth/unlink-line", adaptLegacyHandler(() => import("@/server/api/auth/unlink-line/route"), "DELETE"))
  .get("/auth/verify-guest", adaptLegacyHandler(() => import("@/server/api/auth/verify-guest/route"), "GET"))
  .post("/catalog/cart-availability", adaptLegacyHandler(() => import("@/server/api/catalog/cart-availability/route"), "POST"))
  .get("/catalog/sync", adaptLegacyHandler(() => import("@/server/api/catalog/sync/route"), "GET"))
  .post("/catalog/sync", adaptLegacyHandler(() => import("@/server/api/catalog/sync/route"), "POST"))
  .get("/customer/project-status", adaptLegacyHandler(() => import("@/server/api/customer/project-status/route"), "GET"))
  .get("/customer/warranty-card", adaptLegacyHandler(() => import("@/server/api/customer/warranty-card/route"), "GET"))
  .get("/external-access/session", adaptLegacyHandler(() => import("@/server/api/external-access/session/route"), "GET"))
  .post("/external-access/session", adaptLegacyHandler(() => import("@/server/api/external-access/session/route"), "POST"))
  .delete("/external-access/session", adaptLegacyHandler(() => import("@/server/api/external-access/session/route"), "DELETE"))
  .post("/feedback/website", adaptLegacyHandler(() => import("@/server/api/feedback/website/route"), "POST"))
  .post("/guest/session", adaptLegacyHandler(() => import("@/server/api/guest/session/route"), "POST"))
  .delete("/guest/session", adaptLegacyHandler(() => import("@/server/api/guest/session/route"), "DELETE"))
  .get("/health/live", adaptLegacyHandler(() => import("@/server/api/health/live/route"), "GET"))
  .get("/health", adaptLegacyHandler(() => import("@/server/api/health/route"), "GET"))
  .get("/installations/projects/:proposalId/snapshot", adaptLegacyHandler(() => import("@/server/api/installations/projects/[proposalId]/snapshot/route"), "GET"))
  .get("/media/video", adaptLegacyHandler(() => import("@/server/api/media/video/route"), "GET"))
  .post("/method/create_feedback", adaptLegacyHandler(() => import("@/server/api/method/create_feedback/route"), "POST"))
  .post("/payments/verify-slip", adaptLegacyHandler(() => import("@/server/api/payments/verify-slip/route"), "POST"))
  .delete("/privacy/account", adaptLegacyHandler(() => import("@/server/api/privacy/account/route"), "DELETE"))
  .get("/privacy/consent", adaptLegacyHandler(() => import("@/server/api/privacy/consent/route"), "GET"))
  .post("/privacy/consent", adaptLegacyHandler(() => import("@/server/api/privacy/consent/route"), "POST"))
  .get("/privacy/export", adaptLegacyHandler(() => import("@/server/api/privacy/export/route"), "GET"))
  .patch("/proposals/:proposalId/approval", adaptLegacyHandler(() => import("@/server/api/proposals/[proposalId]/approval/route"), "PATCH"))
  .get("/proposals/:proposalId/native-pdf", adaptLegacyHandler(() => import("@/server/api/proposals/[proposalId]/native-pdf/route"), "GET"))
  .get("/proposals/:proposalId/portal-snapshot", adaptLegacyHandler(() => import("@/server/api/proposals/[proposalId]/portal-snapshot/route"), "GET"))
  .get("/proposals/:proposalId/signed-document", adaptLegacyHandler(() => import("@/server/api/proposals/[proposalId]/signed-document/route"), "GET"))
  .post("/proposals/delivery-document-upload", adaptLegacyHandler(() => import("@/server/api/proposals/delivery-document-upload/route"), "POST"))
  .post("/proposals/delivery-documents/:documentId/archive", adaptLegacyHandler(() => import("@/server/api/proposals/delivery-documents/[documentId]/archive/route"), "POST"))
  .post("/proposals/document-request-info", adaptLegacyHandler(() => import("@/server/api/proposals/document-request-info/route"), "POST"))
  .post("/proposals/document-request-upload", adaptLegacyHandler(() => import("@/server/api/proposals/document-request-upload/route"), "POST"))
  .post("/proposals/field-upload", adaptLegacyHandler(() => import("@/server/api/proposals/field-upload/route"), "POST"))
  .post("/proposals/portal-payment-slip", adaptLegacyHandler(() => import("@/server/api/proposals/portal-payment-slip/route"), "POST"))
  .post("/proposals/portal-revision-request", adaptLegacyHandler(() => import("@/server/api/proposals/portal-revision-request/route"), "POST"))
  .post("/proposals/portal-session", adaptLegacyHandler(() => import("@/server/api/proposals/portal-session/route"), "POST"))
  .delete("/proposals/portal-session", adaptLegacyHandler(() => import("@/server/api/proposals/portal-session/route"), "DELETE"))
  .post("/proposals/project-warranty-registration", adaptLegacyHandler(() => import("@/server/api/proposals/project-warranty-registration/route"), "POST"))
  .post("/proposals/survey-upload", adaptLegacyHandler(() => import("@/server/api/proposals/survey-upload/route"), "POST"))
  .post("/proposals/upload-revision", adaptLegacyHandler(() => import("@/server/api/proposals/upload-revision/route"), "POST"))
  .post("/proposals/upload-signed", adaptLegacyHandler(() => import("@/server/api/proposals/upload-signed/route"), "POST"))
  .post("/quotation/create", adaptLegacyHandler(() => import("@/server/api/quotation/create/route"), "POST"))
  .get("/quotations/:id", adaptLegacyHandler(() => import("@/server/api/quotations/[id]/route"), "GET"))
  .patch("/quotations/:id", adaptLegacyHandler(() => import("@/server/api/quotations/[id]/route"), "PATCH"))
  .post("/quotations/erpnext-sync", adaptLegacyHandler(() => import("@/server/api/quotations/erpnext-sync/route"), "POST"))
  .post("/quotations/sign", adaptLegacyHandler(() => import("@/server/api/quotations/sign/route"), "POST"))
  .get("/realtime/poll", adaptLegacyHandler(() => import("@/server/api/realtime/poll/route"), "GET"))
  .get("/realtime/stream", adaptLegacyHandler(() => import("@/server/api/realtime/stream/route"), "GET"))
  .get("/refunds/:id/credit-note", adaptLegacyHandler(() => import("@/server/api/refunds/[id]/credit-note/route"), "GET"))
  .get("/requests", adaptLegacyHandler(() => import("@/server/api/requests/route"), "GET"))
  .post("/requests", adaptLegacyHandler(() => import("@/server/api/requests/route"), "POST"))
  .post("/services/analytics", adaptLegacyHandler(() => import("@/server/api/services/analytics/route"), "POST"))
  .post("/services/book", adaptLegacyHandler(() => import("@/server/api/services/book/route"), "POST"))
  .get("/services/config", adaptLegacyHandler(() => import("@/server/api/services/config/route"), "GET"))
  .post("/services/confirm", adaptLegacyHandler(() => import("@/server/api/services/confirm/route"), "POST"))
  .get("/services/geocode", adaptLegacyHandler(() => import("@/server/api/services/geocode/route"), "GET"))
  .post("/services/geocode", adaptLegacyHandler(() => import("@/server/api/services/geocode/route"), "POST"))
  .get("/services/location/search", adaptLegacyHandler(() => import("@/server/api/services/location/search/route"), "GET"))
  .post("/services/multi-quote", adaptLegacyHandler(() => import("@/server/api/services/multi-quote/route"), "POST"))
  .get("/services/orders/:orderId/payment-slip", adaptLegacyHandler(() => import("@/server/api/services/orders/[orderId]/payment-slip/route"), "GET"))
  .post("/services/orders/:orderId/payment-slip", adaptLegacyHandler(() => import("@/server/api/services/orders/[orderId]/payment-slip/route"), "POST"))
  .post("/services/portal/claim-intent", adaptLegacyHandler(() => import("@/server/api/services/portal/claim-intent/route"), "POST"))
  .post("/services/portal/recover", adaptLegacyHandler(() => import("@/server/api/services/portal/recover/route"), "POST"))
  .post("/services/portal/session", adaptLegacyHandler(() => import("@/server/api/services/portal/session/route"), "POST"))
  .post("/services/portal/share-link", adaptLegacyHandler(() => import("@/server/api/services/portal/share-link/route"), "POST"))
  .get("/services/portal/status", adaptLegacyHandler(() => import("@/server/api/services/portal/status/route"), "GET"))
  .post("/services/quote", adaptLegacyHandler(() => import("@/server/api/services/quote/route"), "POST"))
  .get("/settings/website", adaptLegacyHandler(() => import("@/server/api/settings/website/route"), "GET"))
  .get("/sso", adaptLegacyHandler(() => import("@/server/api/sso/route"), "GET"))
  .get("/system/feature-flags", adaptLegacyHandler(() => import("@/server/api/system/feature-flags/route"), "GET"))
  .patch("/system/feature-flags", adaptLegacyHandler(() => import("@/server/api/system/feature-flags/route"), "PATCH"))
  .get("/thai-address/lookup", adaptLegacyHandler(() => import("@/server/api/thai-address/lookup/route"), "GET"))
  .post("/track-request", adaptLegacyHandler(() => import("@/server/api/track-request/route"), "POST"))
  .get("/track/:id", adaptLegacyHandler(() => import("@/server/api/track/[id]/route"), "GET"))
  .post("/track/magic-link", adaptLegacyHandler(() => import("@/server/api/track/magic-link/route"), "POST"))
  .post("/track/recover", adaptLegacyHandler(() => import("@/server/api/track/recover/route"), "POST"))
  .get("/users/preferences", adaptLegacyHandler(() => import("@/server/api/users/preferences/route"), "GET"))
  .patch("/users/preferences", adaptLegacyHandler(() => import("@/server/api/users/preferences/route"), "PATCH"))
  .get("/v2/customer/assets", adaptLegacyHandler(() => import("@/server/api/v2/customer/assets/route"), "GET"))
  .get("/v2/customer/projects/:projectId", adaptLegacyHandler(() => import("@/server/api/v2/customer/projects/[projectId]/route"), "GET"))
  .get("/v2/customer/projects", adaptLegacyHandler(() => import("@/server/api/v2/customer/projects/route"), "GET"))
  .get("/v2/customer/service-cases/:caseId", adaptLegacyHandler(() => import("@/server/api/v2/customer/service-cases/[caseId]/route"), "GET"))
  .get("/v2/customer/service-cases", adaptLegacyHandler(() => import("@/server/api/v2/customer/service-cases/route"), "GET"))
  .post("/v2/customer/service-cases", adaptLegacyHandler(() => import("@/server/api/v2/customer/service-cases/route"), "POST"))
  .get("/v2/customer/warranties", adaptLegacyHandler(() => import("@/server/api/v2/customer/warranties/route"), "GET"))
  .get("/v2/guest/warranty/access/:token", adaptLegacyHandler(() => import("@/server/api/v2/guest/warranty/access/[token]/route"), "GET"))
  .post("/v2/guest/warranty/request", adaptLegacyHandler(() => import("@/server/api/v2/guest/warranty/request/route"), "POST"))
  .post("/v2/guest/warranty/revoke", adaptLegacyHandler(() => import("@/server/api/v2/guest/warranty/revoke/route"), "POST"))
  .post("/v2/guest/warranty/verify", adaptLegacyHandler(() => import("@/server/api/v2/guest/warranty/verify/route"), "POST"))
  .get("/weather/solar", adaptLegacyHandler(() => import("@/server/api/weather/solar/route"), "GET"))
  .post("/webhook", adaptLegacyHandler(() => import("@/server/api/webhook/route"), "POST"))
  .post("/wizard/estimate-draft", adaptLegacyHandler(() => import("@/server/api/wizard/estimate-draft/route"), "POST"))
  .post("/wizard/financial-report", adaptLegacyHandler(() => import("@/server/api/wizard/financial-report/route"), "POST"))
;

export const customerApiRouteCount = 100;
